services:
  api:
    container_name: fastapi-app
    image: ayushdubeyyy/fastapi:420   #we dont add the build in prod, because we will be simply pulling the dev code from dockerhub
    depends_on:
      - postgres
    ports:
      - 8000:8000
    #command: uvicorn app.main:app --host 0.0.0.0 --port 8000 
    env_file:
      - .env

  postgres:
    image: postgres 
    environment:
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
        
    volumes:
         - postgres-db:/var/lib/postgresql

volumes:
    postgres-db:

